### ISSUE TITLE
Add site title and favicon

### ISSUE THREAD

**Issue by nelsontky** [CS3219-SE-Principles-and-Patterns/cs3219-project-ay2122-2122-s1-g34#67]
![image](https://user-images.githubusercontent.com/7272103/140508116-f18f9edf-e6a1-456e-989e-6684a249ce2d.png)
Currently, we are still using React's default favicon and title. We should change it to something more recognizable.

**Comment by pasha-292** [comment]
Okay, I'll do these parts.
