### ISSUE TITLE
email cannot be changed in account page

### ISSUE THREAD

**Issue by mchua028** [CS3219-SE-Principles-and-Patterns/cs3219-project-ay2122-2122-s1-g34#71]
valid email given but always show 'Unspecified error orccurred'

**Comment by nelsontky** [comment]
Thank you for pointing that out. I Have found the issue to be due to the need to re-login and I will be providing a solution soon.
![image](https://user-images.githubusercontent.com/7272103/140646524-5a652f86-a999-4039-87b3-07f6070857a9.png)
